// <auto-generated />
using System;
using Inventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inventory.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210711032434_AddTableBarang")]
    partial class AddTableBarang
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Inventory.Models.Barang.Barang", b =>
                {
                    b.Property<Guid>("IdBarang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDaerah")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdStesen")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TarikhSerah")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarikhTamat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarikhTerima")
                        .HasColumnType("datetime2");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("IdBarang");

                    b.ToTable("Barang");
                });

            modelBuilder.Entity("Inventory.Models.Daerah.Daerah", b =>
                {
                    b.Property<Guid>("IdDaerah")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDaerah");

                    b.ToTable("Daerah");
                });

            modelBuilder.Entity("Inventory.Models.Stesen.Stesen", b =>
                {
                    b.Property<long>("IdStesen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("IdDaerah")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStesen");

                    b.ToTable("Stesen");
                });
#pragma warning restore 612, 618
        }
    }
}
